# 1. Data Types
* Integer
* Floating number
* Boolean
* String

In [2]:
x1 = 1
x2 = 1.5
x3 = True
x4 = 'apple'

display(type(x1), type(x2), type(x3), type(x4))  # display() print out everything nicely

int

float

bool

str

# 2.  Data Structures

We will cover the following python data structures. 

* Sequence - list
* Set
* Array
* Dictionary

## 2.1 Sequence - list

All sequence data (e.g.,list, range, string) can be looped over. We will cover list here only. 

- A list is an **ordered** and **changeable** collection of **items**, it contains values of **different types** and **allows duplicate members**.

In [3]:
lst1 = [True, "apple", 3.0, 4, 'apple']    # create a list with different data types

type(lst1)

list

In [4]:
lst1[0]         # select a value from a list 

True

In [5]:
lst1[2:]        # select a range of values 

[3.0, 4, 'apple']

In [6]:
lst1.count('apple')        # count the frequency of a value in a list

2

In [7]:
lst1.index('apple')        # find index of the first occurrence of a value in a list

1

**Modify a list**

Note that the original list will be updated after the operation.

In [8]:
lst1[0] = False                  # replace a value using the assignment operator (=)

lst1

[False, 'apple', 3.0, 4, 'apple']

In [9]:
lst1.insert(2, "watermelon")    # insert a value in 3rd position

lst1

[False, 'apple', 'watermelon', 3.0, 4, 'apple']

In [10]:
lst1.append(12)                 # append a value in the end

lst1

[False, 'apple', 'watermelon', 3.0, 4, 'apple', 12]

In [11]:
lst1.remove("watermelon")      # remove a value

lst1

[False, 'apple', 3.0, 4, 'apple', 12]

**Sort a list**

Again,  the original list will be updated after the operation.

In [12]:
lst2 = [100, 50, 65, 82, 23]
lst2.sort()              # sort in ascending order(default)

lst2 

[23, 50, 65, 82, 100]

In [13]:
lst2.sort(reverse=True)  # sort in descending order

lst2

[100, 82, 65, 50, 23]

**Join two lists**

In [14]:
lst1 + lst2   

[False, 'apple', 3.0, 4, 'apple', 12, 100, 82, 65, 50, 23]

**Loop over a list and list comprehension**

Loop through a list named `fruits` and return a new list with values that contains the character ``"a"``.

In [15]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]   # create a list named fruits

fruits

['apple', 'banana', 'cherry', 'kiwi', 'mango']

In [16]:
newlist = []                    # create a empty list to contain new values

for x in fruits:                # loop over each value(x) in the list(fruits)  
    if "a" in x:                # check with membership operator
        newlist.append(x)       # if true, append the value in the end of newlist 

newlist    

['apple', 'banana', 'mango']

List comprehension offers a shorter syntax when you want to create a new list based on an existing list.

In [17]:
[x for x in fruits if "a" in x]   # alternatively, use list comprehension

['apple', 'banana', 'mango']

<font color=red>***Exercise 1: Your Codes Here***</font>  


Task: loop over every value in ``lst1``, which we created in the 2nd block,  return another list which contains only `str` data, use either for loop or list comprehension.  
- *Hints: use ``type()`` to check data type of a variable (e.g., `x`), use ``==`` or ``is`` for comparison, e.g. ``type(x) == str``*

In [41]:
lst1
print(lst1)
lst_str =[]

print("===========")

for x in lst1:
    if type(x) is str:
        lst_str.append(x)


print("=========== answer below ===========")
lst_str



[False, 'apple', 3.0, 4, 'apple', 12]
=========== answer below ===========


['apple', 'apple']

## 2.2 Sets


A set is an **unordered**, **unchangeable** , and  **unindexed** collection of **unique items** (can be of different data type).  No duplicate members allowed.

- *Note: although set data is unchangeable, we can remove and add items.*

In [18]:
set1 = {"apple", "banana", "cherry"}   # same as set(["apple", "banana", "cherry"]) 

set1  

{'apple', 'banana', 'cherry'}

In [ ]:
#set1[0]               # error: set is unindexed and unchangeable
# set1[0] will show error as set can not be indexed, set[ x ] is a indexing behaviour


TypeError: 'set' object is not subscriptable

**Set operations**

union, intersection, difference, symmetric difference

In [20]:
set2 = {"apple", "mango" , "orange"}   # create a new set

set2

{'apple', 'mango', 'orange'}

In [ ]:
# set1 = {"apple", "banana", "cherry"} 
# set2 = {"apple", "mango" , "orange"}

set1.union(set2)                     # join two sets

{'apple', 'banana', 'cherry', 'mango', 'orange'}

In [22]:
set1.intersection(set2)              # return items apeared in both sets

{'apple'}

In [23]:
set1.difference(set2)                # returns items appeared in set1 but not set2 

{'banana', 'cherry'}

In [24]:
set1.symmetric_difference(set2)      # return items in either set1 or set2 but not both 

{'banana', 'cherry', 'mango', 'orange'}

## 2.3 NumPy Arrays

To host data values of the **same type**, the built-in ``array`` module (available since Python 3.3) can be used.  A more more useful tool is the ``NumPy`` package (check the [Documentation](https://numpy.org/doc/stable/index.html)).

You may need to install the package first:
```python
>>>pip install numpy
```

**1D Array**

1D array can be looped through as a sequence.

In [25]:
import numpy as np                      # make sure numpy has been installed first

arr1 = np.array([1, 4, 2, 5, 3])        # create an integer array

display(arr1, arr1.shape)               # display its values and check its shape

array([1, 4, 2, 5, 3])

(5,)

In [26]:
display(arr1[0], arr1[:3])              # select a value and a range of values,  from the 1D array

1

array([1, 4, 2])

In [27]:
np.arange(0, 20, 2)                     # create an 1D array with numbers in a range: (start, stop-excluded, stepsize)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
np.array([3.14, 4, 2, 3,'string'])     # if data types do not match, NumPy will upcast if possible.

array(['3.14', '4', '2', '3', 'string'], dtype='<U32')

**2D Array**

Arrays can be multi-dimensional, here let's focus on 2D array (matrix) only.

In [29]:
arr2 = np.array([[1,2,3],[2,3,4]])         # create a 2D array (matrix), what's the shape? 

display(arr2, arr2.shape)

array([[1, 2, 3],
       [2, 3, 4]])

(2, 3)

Select values in the 1st row, 1st col, and a particular value in row 1 & col 2.

In [30]:
display(arr2[0,:], arr2[:,0], arr2[0,1])    # arr2[0,:] is same as arr2[0]

array([1, 2, 3])

array([1, 2])

2

**Reshape an array**

In [31]:
arr3 = np.array([3,6,5,1,4,2])      # create a 1D array

arr3_2D = arr3.reshape(2,3)         # reshape it as 2D (2 rows, 3 columns)

display(arr3_2D, arr3_2D.shape)

array([[3, 6, 5],
       [1, 4, 2]])

(2, 3)

**Array operations**

In [32]:
arr3_2D[0,1] = 0             # modify a particular value 

arr3_2D

array([[3, 0, 5],
       [1, 4, 2]])

In [33]:
arr3_2D/10                   # elment-wise computation 

array([[0.3, 0. , 0.5],
       [0.1, 0.4, 0.2]])

<font color=red>***Exercise 2: Your Codes Here***</font>  

- Task 1: please create an 1D array named ``arr4`` with 20 values starting with 5 and stopping at 100 (inclusive), stepsize at 5.
- Task 2: reshape ``arr4`` as 2D ``arr4_2D`` with 5 rows and 4 columns.
- Task 3: multiply each value in ``arr4_2D`` by 3 and then minus 10, display the final result.

In [58]:
print("====== Task 1 =====")
arr4 = np.arange(5,105,5)
print(arr4)

print("")
print("====== Task 2 =====")
print(arr4.shape)
arr4_2D = arr4.reshape(5,4)
print(arr4_2D)
print(arr4_2D.shape)

print("")
print("====== Task 3 =====")
print(arr4_2D /10)





====== Task 1 =====
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]

====== Task 2 =====
(20,)
[[  5  10  15  20]
 [ 25  30  35  40]
 [ 45  50  55  60]
 [ 65  70  75  80]
 [ 85  90  95 100]]
(5, 4)

====== Task 3 =====
[[ 0.5  1.   1.5  2. ]
 [ 2.5  3.   3.5  4. ]
 [ 4.5  5.   5.5  6. ]
 [ 6.5  7.   7.5  8. ]
 [ 8.5  9.   9.5 10. ]]


## 2.4 Dictionary

Dictionaries hold data in (key, value) pairs, each can be in different data type and length.

In [34]:
cars = {"brand": "Ford",
        "electric": False,
        "year": 1964,
        "colors": ["red", "white", "blue"]}

cars

{'brand': 'Ford',
 'electric': False,
 'year': 1964,
 'colors': ['red', 'white', 'blue']}

In [35]:
cars["colors"]             # index values using their key, same as cars.get("colors")

['red', 'white', 'blue']

In [36]:
cars["colors"] = "white"   # modify values with its key
cars

{'brand': 'Ford', 'electric': False, 'year': 1964, 'colors': 'white'}

In [37]:
cars["price"] = 50000     # add an key-value pair 
cars 

{'brand': 'Ford',
 'electric': False,
 'year': 1964,
 'colors': 'white',
 'price': 50000}

In [38]:
cars.pop("year")         # remove a key-value pair
cars

{'brand': 'Ford', 'electric': False, 'colors': 'white', 'price': 50000}

**Useful Notes for Group Project**

JSON data is organized in key-value pairs (i.e., objects) and ordered lists of values (i.e., arrays).

- Objects: Represented by curly braces {}, objects contain key-value pairs (i.e., dictionary data).
- Arrays: Represented by square brackets [], arrays contain ordered lists of values (i.e., objects) separated by commas.

The following codes display how to read the `luxury_cosmetics_popups.json` file (one of project data).
```python
import json

# Open and read the JSON file (make sure the file in the folder where this notebook is located)
with open('luxury_cosmetics_popups.json', 'r') as file:
    data = json.load(file)

# Display the number of objects and the first object 
display(len(data), data[0])
```